"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SpeakerOnIcon = exports.VideoIcon = exports.UserIcon = exports.UploadCloudIcon = exports.Tv2Icon = exports.TvIcon = exports.TrophyIcon = exports.TrashIcon = exports.ThumbsUpIcon = exports.ThumbsDownIcon = exports.SunIcon = exports.StarIcon = exports.SparklesIcon = exports.Share2Icon = exports.SendIcon = exports.SearchIcon = exports.RefreshCwIcon = exports.PlayCircleIcon = exports.PencilIcon = exports.MoonIcon = exports.MicIcon = exports.MessageSquareIcon = exports.MenuIcon = exports.LogOutIcon = exports.LoaderIcon = exports.LinkIcon = exports.LightbulbIcon = exports.InfoIcon = exports.ImageIcon = exports.HomeIcon = exports.HelpCircleIcon = exports.GitBranchIcon = exports.FireIcon = exports.FileTextIcon = exports.FileJsonIcon = exports.EyeOffIcon = exports.EyeIcon = exports.DownloadIcon = exports.DatabaseIcon = exports.CookingPotIcon = exports.CoffeeIcon = exports.ClockIcon = exports.CheckCircleIcon = exports.BotIcon = exports.BookOpenIcon = exports.BarChartIcon = exports.ArrowUpIcon = exports.ArrowLeftIcon = exports.ArrowDownIcon = exports.AlertTriangleIcon = void 0;
exports.XCircleIcon = exports.XIcon = exports.SpeakerOffIcon = void 0;
// This file re-exports icons from the lucide-react library for consistent use throughout the application.
// Using a central file like this makes it easy to manage and swap icons in the future.
var lucide_react_1 = require("lucide-react");
Object.defineProperty(exports, "AlertTriangleIcon", { enumerable: true, get: function () { return lucide_react_1.AlertTriangle; } });
Object.defineProperty(exports, "ArrowDownIcon", { enumerable: true, get: function () { return lucide_react_1.ArrowDown; } });
Object.defineProperty(exports, "ArrowLeftIcon", { enumerable: true, get: function () { return lucide_react_1.ArrowLeft; } });
Object.defineProperty(exports, "ArrowUpIcon", { enumerable: true, get: function () { return lucide_react_1.ArrowUp; } });
Object.defineProperty(exports, "BarChartIcon", { enumerable: true, get: function () { return lucide_react_1.BarChart; } });
Object.defineProperty(exports, "BookOpenIcon", { enumerable: true, get: function () { return lucide_react_1.BookOpen; } });
Object.defineProperty(exports, "BotIcon", { enumerable: true, get: function () { return lucide_react_1.Bot; } });
Object.defineProperty(exports, "CheckCircleIcon", { enumerable: true, get: function () { return lucide_react_1.CheckCircle; } });
Object.defineProperty(exports, "ClockIcon", { enumerable: true, get: function () { return lucide_react_1.Clock; } });
Object.defineProperty(exports, "CoffeeIcon", { enumerable: true, get: function () { return lucide_react_1.Coffee; } });
Object.defineProperty(exports, "CookingPotIcon", { enumerable: true, get: function () { return lucide_react_1.CookingPot; } });
Object.defineProperty(exports, "DatabaseIcon", { enumerable: true, get: function () { return lucide_react_1.Database; } });
Object.defineProperty(exports, "DownloadIcon", { enumerable: true, get: function () { return lucide_react_1.Download; } });
Object.defineProperty(exports, "EyeIcon", { enumerable: true, get: function () { return lucide_react_1.Eye; } });
Object.defineProperty(exports, "EyeOffIcon", { enumerable: true, get: function () { return lucide_react_1.EyeOff; } });
Object.defineProperty(exports, "FileJsonIcon", { enumerable: true, get: function () { return lucide_react_1.FileJson; } });
Object.defineProperty(exports, "FileTextIcon", { enumerable: true, get: function () { return lucide_react_1.FileText; } });
Object.defineProperty(exports, "FireIcon", { enumerable: true, get: function () { return lucide_react_1.Flame; } });
Object.defineProperty(exports, "GitBranchIcon", { enumerable: true, get: function () { return lucide_react_1.GitBranch; } });
Object.defineProperty(exports, "HelpCircleIcon", { enumerable: true, get: function () { return lucide_react_1.HelpCircle; } });
Object.defineProperty(exports, "HomeIcon", { enumerable: true, get: function () { return lucide_react_1.Home; } });
Object.defineProperty(exports, "ImageIcon", { enumerable: true, get: function () { return lucide_react_1.Image; } });
Object.defineProperty(exports, "InfoIcon", { enumerable: true, get: function () { return lucide_react_1.Info; } });
Object.defineProperty(exports, "LightbulbIcon", { enumerable: true, get: function () { return lucide_react_1.Lightbulb; } });
Object.defineProperty(exports, "LinkIcon", { enumerable: true, get: function () { return lucide_react_1.Link; } });
Object.defineProperty(exports, "LoaderIcon", { enumerable: true, get: function () { return lucide_react_1.Loader2; } });
Object.defineProperty(exports, "LogOutIcon", { enumerable: true, get: function () { return lucide_react_1.LogOut; } });
Object.defineProperty(exports, "MenuIcon", { enumerable: true, get: function () { return lucide_react_1.Menu; } });
Object.defineProperty(exports, "MessageSquareIcon", { enumerable: true, get: function () { return lucide_react_1.MessageSquare; } });
Object.defineProperty(exports, "MicIcon", { enumerable: true, get: function () { return lucide_react_1.Mic; } });
Object.defineProperty(exports, "MoonIcon", { enumerable: true, get: function () { return lucide_react_1.Moon; } });
Object.defineProperty(exports, "PencilIcon", { enumerable: true, get: function () { return lucide_react_1.Pencil; } });
Object.defineProperty(exports, "PlayCircleIcon", { enumerable: true, get: function () { return lucide_react_1.PlayCircle; } });
Object.defineProperty(exports, "RefreshCwIcon", { enumerable: true, get: function () { return lucide_react_1.RefreshCw; } });
Object.defineProperty(exports, "SearchIcon", { enumerable: true, get: function () { return lucide_react_1.Search; } });
Object.defineProperty(exports, "SendIcon", { enumerable: true, get: function () { return lucide_react_1.Send; } });
Object.defineProperty(exports, "Share2Icon", { enumerable: true, get: function () { return lucide_react_1.Share2; } });
Object.defineProperty(exports, "SparklesIcon", { enumerable: true, get: function () { return lucide_react_1.Sparkles; } });
Object.defineProperty(exports, "StarIcon", { enumerable: true, get: function () { return lucide_react_1.Star; } });
Object.defineProperty(exports, "SunIcon", { enumerable: true, get: function () { return lucide_react_1.Sun; } });
Object.defineProperty(exports, "ThumbsDownIcon", { enumerable: true, get: function () { return lucide_react_1.ThumbsDown; } });
Object.defineProperty(exports, "ThumbsUpIcon", { enumerable: true, get: function () { return lucide_react_1.ThumbsUp; } });
Object.defineProperty(exports, "TrashIcon", { enumerable: true, get: function () { return lucide_react_1.Trash2; } });
Object.defineProperty(exports, "TrophyIcon", { enumerable: true, get: function () { return lucide_react_1.Trophy; } });
Object.defineProperty(exports, "TvIcon", { enumerable: true, get: function () { return lucide_react_1.Tv; } });
Object.defineProperty(exports, "Tv2Icon", { enumerable: true, get: function () { return lucide_react_1.Tv2; } });
Object.defineProperty(exports, "UploadCloudIcon", { enumerable: true, get: function () { return lucide_react_1.UploadCloud; } });
Object.defineProperty(exports, "UserIcon", { enumerable: true, get: function () { return lucide_react_1.User; } });
Object.defineProperty(exports, "VideoIcon", { enumerable: true, get: function () { return lucide_react_1.Video; } });
Object.defineProperty(exports, "SpeakerOnIcon", { enumerable: true, get: function () { return lucide_react_1.Volume2; } });
Object.defineProperty(exports, "SpeakerOffIcon", { enumerable: true, get: function () { return lucide_react_1.VolumeX; } });
Object.defineProperty(exports, "XIcon", { enumerable: true, get: function () { return lucide_react_1.X; } });
Object.defineProperty(exports, "XCircleIcon", { enumerable: true, get: function () { return lucide_react_1.XCircle; } });
